version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-wallet}
      POSTGRES_USER: ${DB_USER:-wallet}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-wallet}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-wallet}
      DB_USER: ${DB_USER:-wallet}
      DB_PASSWORD: ${DB_PASSWORD:-wallet}
      APP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
